#!/usr/bin/env bash

cat .mkctf.yml | shyaml get-value flag > server-files/flag.txt
docker build -t registry.dev.insecurity-insa.fr/insecurity/config-creator .
docker build -t registry.dev.insecurity-insa.fr/insecurity/config-creator-pwned -f Dockerfile_pwned .
docker push registry.dev.insecurity-insa.fr/insecurity/config-creator
docker push registry.dev.insecurity-insa.fr/insecurity/config-creator-pwned
