#!/usr/bin/env bash

cat .mkctf.yml | shyaml get-value flag > server-files/flag.txt
docker build -t registry.dev.insecurity-insa.fr/insecurity/opensource-as-a-service .
docker build -t registry.dev.insecurity-insa.fr/insecurity/opensource-as-a-service-pwned -f Dockerfile_pwned .
docker push registry.dev.insecurity-insa.fr/insecurity/opensource-as-a-service
docker push registry.dev.insecurity-insa.fr/insecurity/opensource-as-a-service-pwned
