#!/usr/bin/env bash
echo -n DOCKER_PASSWORD? ; read DOCKER_PASSWORD
docker run -e DOCKER_PASSWORD=${DOCKER_PASSWORD} -e DOCKER_USER=insecurity -v /var/run/docker.sock:/var/run/docker.sock -p 12345:12345 --rm -it registry.infra.insecurity-insa.fr/insecurity/opensource-as-a-service
